"""initial schema

基线：以 9013b07 的 models（create_all 全量）对空库 autogenerate 生成，
人工核对后入库。覆盖全部 10 张业务表与索引（含 HNSW 向量索引 vector_ip_ops、
uq_node_system_requirement_key 唯一约束）。

Revision ID: 0001_initial
Revises: 
Create Date: 2026-09-06 11:12:34.451799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from pgvector.sqlalchemy import Vector  # noqa: F401  # VECTOR 列类型（autogenerate 需要显式 import）

# revision identifiers, used by Alembic.
revision: str = '0001_initial'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_key',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False, comment='Access Key 哈希（bcrypt，不存明文）'),
    sa.Column('role', sa.String(length=16), nullable=False, comment='业务角色: admin/pm/dev'),
    sa.Column('project_scope', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('\'{"systems":[],"projects":[]}\'::jsonb'), nullable=False, comment='访问范围（两级）：{systems:[...], projects:[...]}；PM 需求按 system 隔离，资产按 project 隔离'),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'active'"), nullable=False, comment='状态: active/revoked'),
    sa.Column('lax_mode', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='审核模式: false=严格(需审批) true=宽松(免审批直接入库)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('revoked_at', sa.DateTime(), nullable=True, comment='吊销时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_access_key_status', 'access_key', ['status'], unique=False)
    op.create_table('approval_batch',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True, comment='归属项目（悬浮 system 需求批次可为空）'),
    sa.Column('batch_type', sa.String(length=64), nullable=False, comment='批次类型: publish_requirement/submit_dev_artifacts/update_requirement_relations/update_node'),
    sa.Column('submitted_by', sa.String(length=128), nullable=False, comment='提交者 Access Key ID'),
    sa.Column('submitter_role', sa.String(length=16), nullable=False, comment='提交者角色: pm/dev'),
    sa.Column('summary', sa.Text(), server_default=sa.text("''"), nullable=False, comment='自动生成的提交摘要'),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'pending_review'"), nullable=False, comment='状态: pending_review/approved/rejected'),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='提交时间'),
    sa.Column('reviewed_by', sa.String(length=128), nullable=True, comment='审核人 Access Key ID'),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True, comment='审核时间'),
    sa.Column('review_comment', sa.Text(), nullable=True, comment='审核意见（拒绝时填写）'),
    sa.Column('conflict_hint', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='冲突检测提示（审批通过时生成）'),
    sa.Column('operation_id', sa.String(length=128), nullable=True, comment='幂等操作标识'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submitted_by', 'batch_type', 'operation_id', name='uq_approval_batch_idempotency')
    )
    op.create_index('idx_approval_batch_status', 'approval_batch', ['project_id', 'status', 'submitted_at'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('actor', sa.String(), nullable=False, comment='操作人 Access Key 标识'),
    sa.Column('action', sa.String(), nullable=False, comment='操作类型: write/update/approve/reject/archive'),
    sa.Column('target_type', sa.String(), nullable=False, comment='目标类型: node/edge/access_key'),
    sa.Column('target_id', sa.UUID(), nullable=True, comment='目标 ID，部分操作无具体目标'),
    sa.Column('project_id', sa.UUID(), nullable=True, comment='归属项目（节点/边写操作维度，admin/access_key 等跨项目操作留空）'),
    sa.Column('operation_id', sa.String(), nullable=True, comment='幂等操作标识（可选）'),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False, comment='操作详情'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='操作时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_actor_created', 'audit_log', ['actor', 'created_at'], unique=False)
    op.create_index('idx_audit_project', 'audit_log', ['project_id'], unique=False)
    op.create_index('idx_audit_target', 'audit_log', ['target_type', 'target_id'], unique=False)
    op.create_table('knowledge_node',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True, comment='所属项目（悬浮需求可为空）'),
    sa.Column('system_id', sa.UUID(), nullable=True, comment='所属 system 域（仅 Requirement 使用）'),
    sa.Column('requirement_key', sa.String(length=64), nullable=True, comment='需求主键（服务端分配，如 HIS-0001），仅 Requirement 使用'),
    sa.Column('type', sa.String(length=32), nullable=False, comment='节点类型: ProjectProfile/Requirement/CodeSnippet/Solution/DesignIntent/Decision/Pitfall'),
    sa.Column('title', sa.Text(), nullable=False, comment='节点标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='节点正文内容'),
    sa.Column('content_vector', Vector(1024), nullable=True, comment='内容向量（Qwen3-Embedding-0.6B，1024 维）'),
    sa.Column('content_tsv', postgresql.TSVECTOR(), nullable=True, comment='全文检索向量（触发器自动维护）'),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False, comment='类型特有属性（schema 规范见 PDD 4.4）'),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False, comment='标签数组'),
    sa.Column('source', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False, comment='来源信息（Agent、工具、原始文档引用）'),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'approved'"), nullable=False, comment='节点状态: approved/archived'),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='版本号，从 1 开始递增'),
    sa.Column('created_by', sa.Text(), nullable=False, comment='提交者 Access Key 标识'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='软删除标记'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('system_id', 'requirement_key', name='uq_node_system_requirement_key')
    )
    op.create_index('idx_node_project_tags', 'knowledge_node', ['tags'], unique=False, postgresql_using='gin')
    op.create_index('idx_node_project_type_status', 'knowledge_node', ['project_id', 'type', 'status'], unique=False)
    op.create_index('idx_node_requirement_key', 'knowledge_node', ['requirement_key'], unique=False)
    op.create_index('idx_node_system_type_status', 'knowledge_node', ['system_id', 'type', 'status'], unique=False)
    op.create_index('idx_node_tsv', 'knowledge_node', ['content_tsv'], unique=False, postgresql_using='gin')
    op.create_index('idx_node_vector', 'knowledge_node', ['content_vector'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 32, 'ef_construction': 400}, postgresql_ops={'content_vector': 'vector_ip_ops'})
    op.create_index(op.f('ix_knowledge_node_system_id'), 'knowledge_node', ['system_id'], unique=False)
    op.create_table('node_embedding',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False, comment='所属知识节点'),
    sa.Column('facet', sa.String(length=64), nullable=False, comment='facet 名: content / 属性键（root_cause 等）'),
    sa.Column('content_vector', Vector(1024), nullable=True, comment='facet 向量（Qwen3-Embedding-0.6B，1024 维）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_node_embedding_node', 'node_embedding', ['node_id'], unique=False)
    op.create_index('idx_node_embedding_node_facet', 'node_embedding', ['node_id', 'facet'], unique=True)
    op.create_index('idx_node_embedding_vector', 'node_embedding', ['content_vector'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 32, 'ef_construction': 400}, postgresql_ops={'content_vector': 'vector_ip_ops'})
    op.create_table('reindex_task',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True, comment='归属项目（悬浮 system 需求节点嵌入任务可为空）'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='pending/running/done/failed'),
    sa.Column('total', sa.Integer(), nullable=True, comment='待重嵌节点总数（运行前统计）'),
    sa.Column('processed', sa.Integer(), nullable=False, comment='已处理节点数'),
    sa.Column('reindexed', sa.Integer(), nullable=False, comment='成功重嵌节点数'),
    sa.Column('error', sa.Text(), nullable=True, comment='失败原因（status=failed 时填充）'),
    sa.Column('target_node_ids', sa.ARRAY(sa.UUID()), nullable=True, comment='指定节点范围（审批异步嵌入场景）；为空=整库重嵌'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='触发者 Access Key ID'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='开始执行时间'),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True, comment='完成/失败时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reindex_task_project_id'), 'reindex_task', ['project_id'], unique=False)
    op.create_table('requirement_counter',
    sa.Column('system_id', sa.UUID(), nullable=False, comment='system 域 ID'),
    sa.Column('last_value', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='该 system 下需求序号当前值'),
    sa.PrimaryKeyConstraint('system_id')
    )
    op.create_table('system',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False, comment='系统域名（唯一）'),
    sa.Column('description', sa.Text(), nullable=False, comment='系统域描述'),
    sa.Column('code', sa.String(length=32), nullable=True, comment='系统前缀编码（用于需求主键前缀，如 HIS）；缺省由 name 派生或回退 SYS'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('system_project',
    sa.Column('system_id', sa.UUID(), nullable=False, comment='system 域 ID'),
    sa.Column('project_id', sa.UUID(), nullable=False, comment='project ID'),
    sa.PrimaryKeyConstraint('system_id', 'project_id')
    )
    op.create_index('idx_system_project_project', 'system_project', ['project_id'], unique=False)
    op.create_table('approval_item',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False, comment='关联的审批批次 ID'),
    sa.Column('seq', sa.Integer(), nullable=False, comment='批次内序号，从 1 开始'),
    sa.Column('item_type', sa.String(length=16), nullable=False, comment='item 类型: node/edge'),
    sa.Column('action', sa.String(length=16), nullable=False, comment='操作: create/update/delete'),
    sa.Column('entity_type', sa.String(length=64), nullable=False, comment='节点类型（Requirement/CodeSnippet/...）或关系类型（implements/conflicts_with/...）'),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='完整内容（审批通过后写入正式存储）'),
    sa.Column('target_id', sa.UUID(), nullable=True, comment='审批通过后写入的实际节点 ID（回填）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['batch_id'], ['approval_batch.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_approval_item_batch', 'approval_item', ['batch_id', 'seq'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_approval_item_batch', table_name='approval_item')
    op.drop_table('approval_item')
    op.drop_index('idx_system_project_project', table_name='system_project')
    op.drop_table('system_project')
    op.drop_table('system')
    op.drop_table('requirement_counter')
    op.drop_index(op.f('ix_reindex_task_project_id'), table_name='reindex_task')
    op.drop_table('reindex_task')
    op.drop_index('idx_node_embedding_vector', table_name='node_embedding', postgresql_using='hnsw', postgresql_with={'m': 32, 'ef_construction': 400}, postgresql_ops={'content_vector': 'vector_ip_ops'})
    op.drop_index('idx_node_embedding_node_facet', table_name='node_embedding')
    op.drop_index('idx_node_embedding_node', table_name='node_embedding')
    op.drop_table('node_embedding')
    op.drop_index(op.f('ix_knowledge_node_system_id'), table_name='knowledge_node')
    op.drop_index('idx_node_vector', table_name='knowledge_node', postgresql_using='hnsw', postgresql_with={'m': 32, 'ef_construction': 400}, postgresql_ops={'content_vector': 'vector_ip_ops'})
    op.drop_index('idx_node_tsv', table_name='knowledge_node', postgresql_using='gin')
    op.drop_index('idx_node_system_type_status', table_name='knowledge_node')
    op.drop_index('idx_node_requirement_key', table_name='knowledge_node')
    op.drop_index('idx_node_project_type_status', table_name='knowledge_node')
    op.drop_index('idx_node_project_tags', table_name='knowledge_node', postgresql_using='gin')
    op.drop_table('knowledge_node')
    op.drop_index('idx_audit_target', table_name='audit_log')
    op.drop_index('idx_audit_project', table_name='audit_log')
    op.drop_index('idx_audit_actor_created', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('idx_approval_batch_status', table_name='approval_batch')
    op.drop_table('approval_batch')
    op.drop_index('idx_access_key_status', table_name='access_key')
    op.drop_table('access_key')
    # ### end Alembic commands ###
